sudo: required

services:
  - docker

before_install:
  - cd backend
  - docker-compose up -d

script:
  - docker-compose run backend ./scripts/wait-for-it.sh db:5432 -t 10
  - docker-compose run backend yarn test

after_script:
  - docker-compose down
