sudo: required

services:
  - docker

before_install:
  - cd backend
  - docker-compose up -d

script:
  - docker-compose run backend ./scripts/wait-for-it.sh db:5432 -t 10
  - docker-compose run -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN backend bash -c "yarn test && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"

after_script:
  - docker-compose down
